#!/bin/sh
### BEGIN INIT INFO
# Provides:          kuryr-server
# Required-Start:    $network $local_fs $remote_fs $syslog
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Kuryr libnetwork server
# Description:       Kuryr libnetwork server
### END INIT INFO

DESC="OpenStack Kuryr Libnetwork server"
PROJECT_NAME=kuryr
NAME=${PROJECT_NAME}-server
